version: "2"
services:
  web:
    build: .
    command: ["python", "server.py"]
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    depends_on:
     - "dataservice"

  dataservice:
    image: nginx:alpine
    volumes:
    - "./dataservice:/usr/share/nginx/html"
    ports:
    - "80:80"
